const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.jumpthru,
		C3.Plugins.Text,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{PularAtravés: 0},
	{Player: 0},
	{Contou: 0},
	{Plataformas: 0},
	{PlacarScore: 0},
	{Sólido: 0},
	{Chao: 0},
	{Universo: 0},
	{FundoFloresta: 0},
	{Placar: 0},
	{Moeda: 0},
	{PlacarMoedas: 0},
	{FundoPlacarMoedas: 0},
	{Porta: 0},
	{Texto: 0},
	{Sprite: 0},
	{Áudio: 0},
	{Teclado: 0},
	{Botão2: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{download: 0},
	{imagesremovebgpreview: 0},
	{Sprite4: 0},
	{botaoJogar: 0},
	{Sprite6: 0},
	{Toque: 0},
	{Fixar: 0},
	{Botaodireito: 0},
	{Botaoesquerdo: 0},
	{Score: 0},
	{Moedas: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Plataformas: class extends self.ISpriteInstance {},
	PlacarScore: class extends self.ITextInstance {},
	Chao: class extends self.ISpriteInstance {},
	Universo: class extends self.ISpriteInstance {},
	FundoFloresta: class extends self.ISpriteInstance {},
	Placar: class extends self.ISpriteInstance {},
	Moeda: class extends self.ISpriteInstance {},
	PlacarMoedas: class extends self.ITextInstance {},
	FundoPlacarMoedas: class extends self.ISpriteInstance {},
	Porta: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Botão2: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	download: class extends self.ISpriteInstance {},
	imagesremovebgpreview: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	botaoJogar: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Botaodireito: class extends self.ISpriteInstance {},
	Botaoesquerdo: class extends self.ISpriteInstance {}
}